# Generated by Django 6.0.5 on 2026-05-24 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
